project:
  type: book
  output-dir: report  #_site

execute:
  cache: false  # true   ## see https://quarto.org/docs/projects/code-execution.html
  freeze: false 
  echo: false

book:
  title: "Regression without regrets"
  author: "M. Baillie, G. Heinze & M. Huebner"
  date: today  ## day report is complied 
  chapters:
  - index.qmd  
  - Bact_intro.qmd # ok
  - Bact_IDA_plan.qmd # ok
  - Bact_analysis_data.qmd ## - needs editing
  - Bact_missing.qmd  # ok
  - Bact_univar.qmd
  - Bact_multivar.qmd
  - Bact_analysis_data_final.qmd
  - references.qmd 
  appendices:
    - Bact_source_data.qmd # ok
    - Bact_descriptives.qmd
    - Bact_suppl.qmd 
    - Pseudo_log_explainer.qmd
  #- SessionInfo.qmd
  
bibliography: references.bib

format:
  # html:
  #    theme: cosmo
  #    css: styles.css
  #    toc: true
  #    code-fold: true
  #    code-tools: true
  #    code-summary: "Show the code"
  docx:
    toc: true
    toc-depth: 2
    number-sections: true
    highlight-style: github
    crossref:
      chapters: true